### PR TITLE
Add header image

### PR DESCRIPTION
**Pull request by kaikreuzer**
Interested in a header image?

### CODE REVIEW

**Comment by florian-h05** [comment]
Sure! Looks fantastic, now I want to travel to Iceland or Norway to see real polar lights ;-)

**Comment by kaikreuzer** [comment]
Any idea what I did wrong here so that the image isn't shown...?

**Comment by florian-h05** [comment]
For me it is shown both with my local preview and with the Netlify deploy preview: https://deploy-preview-435--openhab.netlify.app/blog/

**Comment by kaikreuzer** [comment]
Ok, all fine - I had to clean my browser cache and can now see it as well!

**Pull request merged**
